// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_340_W22SD_Lab4.Models;

#nullable disable

namespace SD_340_W22SD_Lab4.Migrations
{
    [DbContext(typeof(SD340W22SDLab4Context))]
    partial class SD340W22SDLab4ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.Route", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"), 1L, 1);

                    b.Property<bool>("BicycleAccessible")
                        .HasColumnType("bit");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RampAccessible")
                        .HasColumnType("bit");

                    b.HasKey("Number");

                    b.ToTable("Route", (string)null);
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.ScheduledStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RoutenNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("datetime");

                    b.Property<int>("StopNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoutenNumber");

                    b.HasIndex("StopNumber");

                    b.ToTable("ScheduledStop", (string)null);
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.Stop", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"), 1L, 1);

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Number");

                    b.ToTable("Stop", (string)null);
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.ScheduledStop", b =>
                {
                    b.HasOne("SD_340_W22SD_Lab4.Models.Route", "RoutenNumberNavigation")
                        .WithMany("ScheduledStops")
                        .HasForeignKey("RoutenNumber")
                        .IsRequired()
                        .HasConstraintName("FK_ScheduledStop_Route");

                    b.HasOne("SD_340_W22SD_Lab4.Models.Stop", "StopNumberNavigation")
                        .WithMany("ScheduledStops")
                        .HasForeignKey("StopNumber")
                        .IsRequired()
                        .HasConstraintName("FK_ScheduledStop_Stop");

                    b.Navigation("RoutenNumberNavigation");

                    b.Navigation("StopNumberNavigation");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.Route", b =>
                {
                    b.Navigation("ScheduledStops");
                });

            modelBuilder.Entity("SD_340_W22SD_Lab4.Models.Stop", b =>
                {
                    b.Navigation("ScheduledStops");
                });
#pragma warning restore 612, 618
        }
    }
}
